#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

# Remove previous meshes
rm -r constant/polyMesh
rm -r constant/fluid/polyMesh
rm -r constant/reacting/polyMesh
rm -r constant/solid/polyMesh

# Mesh
blockMesh

# Set fluid vs solid regions
topoSet

# Split regions
splitMeshRegions -cellZones -overwrite

# Remove unsplitted mesh
rm -r constant/polyMesh

# Renumbering
renumberMesh -overwrite -region fluid
renumberMesh -overwrite -region reacting
renumberMesh -overwrite -region solid

# Check mesh
checkMesh -region fluid
checkMesh -region reacting
checkMesh -region solid

#------------------------------------------------------------------------------

